CartContext first version
fe-jun24-team4/phone-catalog pull request #29
Opened 2024-09-17 21:05 UTC by piyopiyo0

2024-09-17 21:07 UTC, piyopiyo0 commented
сорі, воно якось дивно закомітилось все разом з попередньою таскою о_о

2024-09-17 21:19 UTC, piyopiyo0 commented
потрібно винести типи та функції в окремі файли, дороблю

2024-09-18 08:16 UTC, Teollan requested changes

2024-09-18 08:16 UTC, Teollan commented on src/pages/CatalogPage/context/CartContext.tsx
Hey! It really cool that you`ve practically recreated Redux, but please rewrite it just with useState and methods so its in line with other contexts in this project.

2024-09-18 08:36 UTC, piyopiyo0 commented on src/pages/CatalogPage/context/CartContext.tsx
Sure, thanks for your comment!

2024-09-18 11:48 UTC, Teollan approved these changes
👍

2024-09-18 11:48 UTC, merged